spring.application.name=travel-tracker

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

restcountries.base-url=https://api.restcountries.com
restcountries.countries-path=/countries/v5
restcountries.api-key=${RESTCOUNTRIES_API_KEY}
restcountries.response-fields=names.common,names.official,codes.alpha_3,codes.alpha_2,capitals.name,flag.url_png,flag.url_svg,region

