spring.application.name=travel-tracker

restcountries.uri=https://api.restcountries.com/countries/v5
restcountries.api-key=${RESTCOUNTRIES_API_KEY}
restcountries.response-fields=names.common,names.official,codes.alpha_3,codes.alpha_2,capitals.name,flag.url_png,flag.url_svg,region

